# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Fs4LdJs4KbeaQHVYTTbJA9Q6zuir-42
"""

print('code for Hello world!')

